export const WEBVIEW_MESSAGES = {
  REQUEST_TOKENS: "REQUEST_TOKENS",
  INJECT_TOKENS: "INJECT_TOKENS",
  TOKEN_REFRESH_FAILED: "TOKEN_REFRESH_FAILED",
  LOGOUT: "LOGOUT",
  DEBUG_LOG: "DEBUG_LOG",
} as const;
